spring.application.name=assingment_springBoot



spring.datasource.url=jdbc:mysql://localhost:5233/college_spring
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true